name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
                  
    - name: Run UnitTests
      id: unit-test
      run: xcodebuild test -project 'Numero.xcodeproj' -scheme 'Numero' -derivedDataPath Build/ -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 8' -enableCodeCoverage YES | xcpretty
      
    - name: Get Line Rate
      id: get_line_rate
      run: swift coverage.swift
      
    - name: Check coverage tolerance
      if: ${{ steps.get_line_rate.outputs.lineRate < 0.9 }}
      uses: actions/github-script@v3
      env:
          COVERAGE: ${{ steps.get_line_rate.outputs.lineRate }}
      with:
        script: |
            core.setFailed('Coverage test below tolerance')
            
    - run: echo "Current Coverage is $COVERAGE"
      
#     - name: Telegram Notification
#       run: bash ./telegram_notification2.sh
#       env:
#         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#         TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
#         ACTION_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
#         TEST_OUTCOME: ${{ steps.unit-test.outcome }}
        
