name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run Script
      run: swift hello.swift
      
    - name: Check coverage tolerance
      if: ${{ 0.8 < 0.9 }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Coverage test below tolerance')
      
    - name: Run UnitTests
      id: unit-test
      run: xcodebuild test -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 8' | xcpretty
      
    - name: Telegram Notification
      run: bash ./telegram_notification2.sh
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        ACTION_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        TEST_OUTCOME: ${{ steps.unit-test.outcome }}
        
