name: Swift

on: push

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run UnitTests
      run: xcodebuild test -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 8'
      
    - name: Debug
      env:
        JOB: ${{ toJson(job) }}
        CONTEXT: ${{ toJson(github) }}
      run: |
        echo $JOB
        echo $CONTEXT
