name: Swift

on: push

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run UnitTests
      id: unit-test
      run: xcodebuild test -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 8'
      
    - name: Telegram Notification
      run: bash ./telegram_notification2.sh
      env:
        ACTION_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        TEST_OUTCOME: ${{ steps.unit-test.outcome }}
        
