name: Swift

on: push

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Run UnitTests
      id: unit-test
      run: xcodebuild test -project 'Numero.xcodeproj' -scheme 'Numero' -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 8'
      
    - name: Result
      run: echo "Result = $OUTCOME"
      env:
        OUTCOME: ${{ steps.unit-test.outcome }}
        
